name: Propose Automated PR

on:
  workflow_dispatch: # Allows manual triggering from the GitHub UI
  # You could also trigger on:
  # push:
  #   branches:
  #     - main
  # schedule:
  #   - cron: '0 0 * * *' # Daily at midnight UTC

jobs:
  update-lockfiles:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Required to push new commits
      pull-requests: write # Required to create a pull request

    steps:
      - name: Set up Python 3.12
        uses: actions/setup-python@v5 # Use the latest version of setup-python

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Required for 'peter-evans/create-pull-request' to push to a new branch
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Make some changes
        working-directory: ci/hermetic
        run: |
          sudo apt-get update && sudo apt-get install -y python3-dnf
          pip3 install requests pyyaml ruamel.yaml
          bash -x update_artifacts_lock_yaml.sh
          bash -x update_rpms_lock_yaml.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # The default GITHUB_TOKEN is sufficient
          commit-message: 'feat(automated): Update the lockfiles'
          title: 'Automated: lockfiles updated'
          body: |
            This PR was automatically generated by the 'Propose Automated PR' workflow.
            It includes a new file created at the time of execution.
          branch: update-lockfile-${{ github.run_number }} # Dynamic branch name
          base: main # The branch to create the PR against (e.g., main, master)
          labels: |
            automated-pr
            enhancement
          delete-branch-after-merge: true
          push-to-fork: jcapiitao/coreos-assembler

