name: Update lockfiles PR

on:
  workflow_dispatch: # Allows manual triggering from the GitHub UI
  schedule:
    - cron: '0 4 * * *' # Daily at 4:00am UTC

jobs:
  update-lockfiles:
    if: github.event.repository.fork == true && github.repository == 'jcapiitao/coreos-assembler'
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write # Required to create a pull request

    steps:
      - name: Set up Python 3.12
        uses: actions/setup-python@v5 # Use the latest version of setup-python

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Required for 'peter-evans/create-pull-request' to push to a new branch
          fetch-depth: 0

      - name: Make some changes
        working-directory: ci/hermetic
        run: |
          sudo apt-get update && sudo apt-get install -y python3-dnf
          pip3 install requests pyyaml ruamel.yaml
          bash -x update_artifacts_lock_yaml.sh
          bash -x update_rpms_lock_yaml.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.UPDATE_LOCKFILES_PAT }}
          commit-message: 'feat(automated): Update the lockfiles'
          title: 'Automated: lockfiles updated'
          body: |
            This PR was automatically generated by the 'Update lockfiles PR' workflow.
            It includes a new file created at the time of execution.
          branch: automated-updates/update-lockfile-${{ github.run_number }} # Dynamic branch name
          base: main # The branch to create the PR against (e.g., main, master)
          labels: |
            automated-pr
            update-lockfiles
          delete-branch-after-merge: true
          push-to-fork: jcapiitao/coreos-assembler
          committer: "CoreOS Bot <coreosbot@fedoraproject.org>"
          author: "CoreOS Bot <coreosbot@fedoraproject.org>"
